name: "Linter"
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Installation
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8
      - name: Lint
        run: flake8 . --exclude=venv,__pycache__,.venv
